# Generated by Django 2.2 on 2020-02-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTaxiAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseFare', models.FloatField()),
                ('vehicleTypeId', models.TextField()),
                ('fromTime', models.TimeField(auto_now_add=True)),
                ('toTime', models.TimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
