# Generated by Django 2.2 on 2020-02-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTaxiAdmin', '0002_faremodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('removeDate', models.DateTimeField(auto_now_add=True)),
                ('cityTaxi', models.TextField()),
                ('licenseNumber', models.TextField()),
                ('licenseAuthorizationDate', models.DateTimeField()),
                ('RegistrationTaxi', models.TextField()),
                ('brand', models.TextField()),
                ('model', models.TextField()),
                ('typeOfvehicle', models.TextField()),
                ('ownerNationalidentitynumber', models.TextField()),
                ('ownerCredentialnumber', models.TextField()),
                ('vtCard', models.BooleanField(default=False)),
                ('buyDate', models.DateTimeField()),
                ('registrationDate', models.DateTimeField()),
                ('lastITVdate', models.DateTimeField()),
                ('lastMetropolitandate', models.DateTimeField()),
                ('lastVerificationdate', models.DateTimeField()),
                ('driverscredentialnumber', models.TextField()),
                ('extraDriverscredentialnumberA', models.TextField()),
                ('extraDriverscredentialnumberB', models.TextField()),
                ('photoOftaxi', models.ImageField(default='default/Image/avater.jpeg', upload_to='Admin/car/PhotoTaxi/')),
                ('codeBluethootradio', models.TextField()),
                ('pets', models.BooleanField(default=False)),
                ('package', models.BooleanField(default=False)),
                ('bluetoothRadio', models.BooleanField(default=False)),
                ('solidarityTaxi', models.BooleanField(default=False)),
                ('handicapedTaxi', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
