# Generated by Django 2.2 on 2020-02-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTaxiAdmin', '0003_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='zipCodeWorkCity',
            field=models.TextField(default=''),
        ),
    ]
