# Generated by Django 2.2 on 2020-02-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTaxiAdmin', '0005_auto_20200209_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='addDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='buyDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='lastITVdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='lastMetropolitandate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='lastVerificationdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='registrationDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='removeDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
