# Generated by Django 2.2 on 2020-01-30 07:49

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.TextField(default='')),
                ('countryCode', models.TextField(default='+91')),
                ('phoneNo', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('removeDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('deviceIMEI', models.TextField(default=[])),
                ('deviceHash', models.TextField(default='')),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('dateOfBirth', models.DateTimeField(auto_now_add=True)),
                ('gender', models.TextField(default='Others')),
                ('address', models.TextField(default='My Address')),
                ('about', models.TextField(default='About User')),
                ('educationalQualification', models.TextField(default='Education')),
                ('paymentMethod', djongo.models.fields.ListField(default=[])),
                ('userOTP', models.TextField()),
                ('userLocation', models.TextField(default='88.4807644, 22.5808643')),
                ('language', models.TextField(default='English')),
                ('favoriteTaxis', djongo.models.fields.ListField(default=[])),
                ('taxisBlocked', djongo.models.fields.ListField(default=[])),
                ('adminNotices', models.TextField(default='Notice')),
                ('clintScore', models.FloatField(default=0.0)),
            ],
        ),
    ]
