# Generated by Django 2.2 on 2020-02-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTaxiUser', '0003_auto_20200130_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bankAccountDetails',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='bankCardDetails',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='handicapedTaxi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='solidarityTaxi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='typeOfClient',
            field=models.CharField(choices=[('GOLD', 'GOLD'), ('SILVER', 'SILVER'), ('BRONZE', 'BRONZE'), ('NONE', 'NONE')], default='', max_length=1),
        ),
    ]
