# Generated by Django 2.2 on 2020-01-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTaxiDriver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='PhotoDNI',
            field=models.ImageField(default='default/Image/avater.jpeg', upload_to='Driver/DriverDNI/'),
        ),
    ]
