# Generated by Django 2.2 on 2020-01-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTaxiDriver', '0002_auto_20200130_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
