# Generated by Django 2.2 on 2020-01-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTaxiDriver', '0003_auto_20200130_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cityOfWork',
            field=models.TextField(default=''),
        ),
    ]
