# Generated by Django 2.2 on 2020-02-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTaxiDriver', '0004_driver_cityofwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='countryCode',
            field=models.TextField(default='+91'),
        ),
    ]
