# Generated by Django 2.2 on 2020-02-03 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.TextField()),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('email', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('postalCode', models.TextField()),
                ('nif', models.TextField()),
                ('administrators', models.TextField()),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('removeDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YouTaxiCompany.Workers')),
            ],
        ),
    ]
