# Generated by Django 2.2 on 2020-02-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTaxiCompany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bankAccountDetails',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='bankCardDetails',
            field=models.TextField(default=False),
        ),
    ]
