# Generated by Django 2.2 on 2020-02-11 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YouTaxiCompany', '0002_auto_20200211_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workres', to='YouTaxiCompany.Workers'),
        ),
    ]
