# Generated by Django 2.2 on 2020-02-11 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YouTaxiCompany', '0003_auto_20200211_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YouTaxiCompany.Workers'),
        ),
    ]
